DROP TABLE IF EXISTS orig_answers_photos;
DROP TABLE IF EXISTS orig_answers;
DROP TABLE IF EXISTS orig_questions;
DROP TABLE IF EXISTS answers_photos;
DROP TABLE IF EXISTS answers;
DROP TABLE IF EXISTS questions;

CREATE TABLE orig_questions (
  id            INTEGER PRIMARY KEY,
  product_id    INTEGER,
  body          TEXT,
  date_written  TIMESTAMPTZ,
  asker_name    TEXT,
  asker_email   TEXT,
  reported      BOOLEAN,
  helpful       INTEGER
);

CREATE TABLE orig_answers (
  answer_id       INTEGER PRIMARY KEY,
  question_id     INTEGER,
  body            TEXT,
  date_written    TIMESTAMPTZ,
  answerer_name   TEXT,
  answerer_email  TEXT,
  reported        BOOLEAN,
  helpful         INTEGER
);

CREATE TABLE orig_answers_photos (
  photo_id     INTEGER PRIMARY KEY,
  answer_id    INTEGER,
  url          TEXT
);

CREATE TABLE questions (
  id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id    INTEGER,
  body          TEXT,
  date_written  TIMESTAMPTZ,
  asker_name    TEXT,
  asker_email   TEXT,
  reported      BOOLEAN DEFAULT false,
  helpful       INTEGER DEFAULT 0
);

CREATE TABLE answers (
  answer_id       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  question_id     INTEGER,
  body            TEXT,
  date_written    TIMESTAMPTZ,
  answerer_name   TEXT,
  answerer_email  TEXT,
  reported        BOOLEAN DEFAULT false,
  helpful         INTEGER DEFAULT 0
);

CREATE TABLE answers_photos (
  photo_id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  answer_id  INTEGER,
  url        TEXT
);

COPY orig_questions FROM '/Users/ErinAntoine/Hack Reactor Bootcamp Files/QA/rawdata/transformed_questions.csv' WITH (FORMAT CSV, HEADER true);

COPY orig_answers FROM '/Users/ErinAntoine/Hack Reactor Bootcamp Files/QA/rawdata/transformed_answers.csv' WITH (FORMAT CSV, HEADER true);

COPY orig_answers_photos FROM '/Users/ErinAntoine/Hack Reactor Bootcamp Files/QA/rawdata/transformed_answers_photos.csv' WITH (FORMAT CSV, HEADER true);

INSERT INTO questions (id, product_id, body, date_written, asker_name, asker_email, reported, helpful)
SELECT id, product_id, body, date_written, asker_name, asker_email, reported, helpful
FROM orig_questions;

INSERT INTO answers (answer_id, question_id, body, date_written, answerer_name, answerer_email, reported, helpful)
SELECT answer_id, question_id, body, date_written, answerer_name, answerer_email, reported, helpful
FROM orig_answers;

INSERT INTO answers_photos (photo_id, answer_id, url)
SELECT photo_id, answer_id, url
FROM orig_answers_photos;